### ISSUE TITLE
CSS display and the Raw plugin

### ISSUE THREAD

**Issue by jmelick** [broadly/wordpress-plugin#7]
Hey Mario-

We had previously done a bit of digging on sites where the code doesn't render properly - and we had solved it with the Raw tag / Raw plugin. However, I'm not sure we had tested it all properly / thought through this. If you look at this site, the raw plugin does it job in the page renders properly - but it also blocks the plugin from running, so the content replacement does not happen properly and the browser just runs the javascript / renders the CSS.

See example below:
With Raw Tags:
http://thetophatter.com/reviews/

Without Raw Tags:
http://thetophatter.com/reviews2/

This site is running WP 3.9.9, so an older version. Can you explore options?

Thanks!

**Comment by mpeshev** [comment]
That's still related to the wpautop problems in some sites, as well as the styling for the br in the theme. It's a tricky problem since different sites behave differently, depending on their settings, theme and set of plugins.

I don't have an explanation about why isn't the plugin triggered here though, something seems to be suppressing it. Has that happened elsewhere else? Seems to be site-specific to me.

**Comment by jmelick** [comment]
It seems the raw tag is suppressing it - will the raw tag always suppress?
Note for this site, raw was not directly supported, so we added a plugin
that added the raw short ode. Perhaps that plugin has a different behavior.


On Sep 30, 2015, at 2:52 PM, Mario Peshev <notifications@github.com> wrote:

That's still related to the wpautop problems in some sites, as well as the
styling for the br in the theme. It's a tricky problem since different
sites behave differently, depending on their settings, theme and set of
plugins.

I don't have an explanation about why isn't the plugin triggered here
though, something seems to be suppressing it. Has that happened elsewhere
else? Seems to be site-specific to me.

—
Reply to this email directly or view it on GitHub
<https://github.com/broadly/wordpress-plugin/issues/7#issuecomment-144552649>
.

**Comment by mpeshev** [comment]
I'll double check. I wrote a small plugin disabling wpautop and it's still applied on the site. It looks like there's something else overriding all of it. 

I would write a custom shortcode that could be used instead of [raw] or a checkbox for disabling wpautop, but removing it globally didn't change anything.

**Comment by mpeshev** [comment]
I tested the Raw HTML plugin locally and it blocked the Broadly plugin as well. The [raw] shortcode plugin I installed worked great for me locally, but still leads to broken markup on the production site. I'll try again tomorrow, but now it still seems more of a site-related thing with br/div-specific styling from the theme and overridden wpautop.

**Comment by jmelick** [comment]
Hi Mario, any update here?

**Comment by mpeshev** [comment]
I spent some time trying different options out, but I can't find a good way to solve that globally in a way that would work across all sites.

Some would have styling issues (like adding huge margins or line-heights that would break the layout), others would strip a good chunk of the wrapped in raw code (and block our dynamic shortcodes), and generally if it works for most cases, it's still affecting some. Especially due to the fact that wpautop is enabled for some WP sites and disabled for others. And the infinite amount of combinations with a theme and plugins. :\

**Comment by jmelick** [comment]
Okay, thanks for update. My takeaway is no simple solution / our code itself is fine. The site in question is an old version - perhaps 4.0.0+ is what we require. We'll continue to keep an eye on this as we add additional sites. 

Closing this issue and moving forward with deploy of new version.

**Comment by mpeshev** [comment]
Correct - let me know in case of a similar problem. We may be able to set some CSS rules that would solve the visual problem in different configurations/themes, but it's been pretty compliant as-is.
